# Generated by Django 2.2.4 on 2020-01-22 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('birth_certificate', models.FileField(db_index=True, upload_to='birth_certificates')),
                ('national_id', models.FileField(db_index=True, upload_to='national_id')),
                ('adress', models.TextField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('school_name', models.CharField(max_length=255)),
                ('school_adress', models.CharField(max_length=300)),
                ('academic_level', models.CharField(max_length=20)),
                ('year_of_completion', models.CharField(max_length=5)),
                ('is_approved', models.BooleanField(default=False)),
                ('sponsor_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('recommendation_letter', models.FileField(db_index=True, upload_to='recommendation_letter')),
                ('applicant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='aplicant', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
