# Generated by Django 2.2.4 on 2020-01-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LA', 'LANDVILLE ADMIN'), ('CA', 'CLIENT ADMIN'), ('BY', 'BUYER')], default='CA', max_length=2, verbose_name='user role'),
        ),
    ]
