# Generated by Django 2.2.4 on 2020-01-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200121_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AP', 'APPLICANT'), ('RC', 'RECEIVER')], default='CA', max_length=2, verbose_name='user role'),
        ),
    ]
