# Generated by Django 2.2.4 on 2020-01-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200122_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AP', 'APPLICANT'), ('ST', 'STAFF'), ('SP', 'SPONSOR')], default='CA', max_length=2, verbose_name='user role'),
        ),
    ]
